//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Collegio_Data" +
            "base.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Collegio_DatabaseConnectionString {
            get {
                return ((string)(this["Collegio_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=E:\\WINDOWSFORMSAPPLICATION1\\WI" +
            "NDOWSFORMSAPPLICATION1\\COLLEGIO_DATABASE.MDF;Integrated Security=True;Connect Ti" +
            "meout=30")]
        public string E__WINDOWSFORMSAPPLICATION1_WINDOWSFORMSAPPLICATION1_COLLEGIO_DATABASE_MDFConnectionString {
            get {
                return ((string)(this["E__WINDOWSFORMSAPPLICATION1_WINDOWSFORMSAPPLICATION1_COLLEGIO_DATABASE_MDFConnect" +
                    "ionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Hamza\\Documents\\Coll" +
            "egio_Database.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Collegio_DatabaseConnectionString1 {
            get {
                return ((string)(this["Collegio_DatabaseConnectionString1"]));
            }
        }
    }
}
